name: Pull Request Check

on: 
  pull_request: 
    types: [opened, synchronize]

jobs:
  check: 
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps: 
      - uses: actions/github-script@v7
        with:
          script: |
            async function run() {
              const pull_request = context.payload.pull_request; // pull_request 객체 가져오기
  
              if (!pull_request) {
                console.log("This is not a pull request"); // console 출력
                return; // 종료
              }
  
              const body = pull_request.body;
  
              if (!body) {
                // PR에 코멘트 추가
                await github.rest.issues.createComment({
                  owner: context.repo.owner, // 저장소 소유자
                  repo: context.repo.repo, // 저장소 이름
                  issue_number: pull_request.number, // PR 번호
                  body: "해당 PR은 가이드라인을 준수하지 않았기 때문에 PR을 닫습니다. 가이드라인을 준수해서 다시 PR 해주세요", // 코멘트 내용
                });
  
                // PR 닫기
                await github.rest.pulls.update({
                  owner: context.repo.owner, // 저장소 소유자
                  repo: context.repo.repo, // 저장소 이름
                  pull_number: pull_request.number, // PR 번호
                  state: "closed", // 상태 변경
                });
              }
            }
            
            run();
